### ISSUE TITLE
Script doesn't run on Debian Stretch

### ISSUE THREAD

**Issue by mlimper** [DGG3D/rapidcompact-scripting#2]
Encountered this error:
![image](https://user-images.githubusercontent.com/1853237/94974405-c8b63f00-050e-11eb-95db-3f4f9504b15b.png)

My python3 version:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
```

**Comment by mlimper** [comment]
@mfpgs any ideas?

**Comment by mlimper** [comment]
Another one that occurs only when the auth cache is there:
```
max@debian:~/Downloads/rapidcompact-scripting-master$ python3 rpdc.py input
API Endpoint: https://api.rapidcompact.com/api/
Logging in...
Traceback (most recent call last):
  File "rpdc.py", line 328, in <module>
    accessToken = login(userCredentials, baseUrl)
  File "rpdc.py", line 112, in login
    cachedToken = loadTokenFromFile(baseUrl)
  File "rpdc.py", line 100, in loadTokenFromFile
    tokenExpiration = datetime.datetime.fromisoformat(auth["expiration"])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by arubertoson** [comment]
Don't know if you had a look at this properly but the functionality you list above is introduced in later python versions.

- **f-strings**: python 3.6
- **datetime.datetime.fromisoformat**: python 3.7

**Comment by mlimper** [comment]
Hey, thanks! That is pretty usefule to know : )

Actually, we have kind of "fixed" that in the latest version by requiring that Python 3.8 or higher is used, which made the problem disappear (as long as you have such a newer version, of course)
https://github.com/DGG3D/rapidcompact-scripting/blob/master/rpdc.py#L4
